version: "3.8"

services:

  n8n:
    image: n8nio/n8n:latest
    volumes:
      - ./n8n_data:/home/node/.n8n
    ports:
      - 5678:5678
    environment:
      - GENERIC_TIMEZONE:"Europe/Paris"
      - TZ:"Europe/Paris"